import React, { useState, useRef } from 'react';
import { AuthorlyEditor, type EditorRef } from '../src';
import '../src/styles/editor.css';
import '../src/styles/renderer.css';

export const PreviewPage: React.FC = () => {
    const editorRef = useRef<EditorRef>(null);
    const [darkMode, setDarkMode] = useState(false);
    const [content, setContent] = useState(`<h1>Direct HTML Preview</h1>
<p>This page previews the HTML generated by the editor directly.</p>
<h2>No AuthorlyRenderer used</h2>
<p>Everything in the preview comes straight from <code>getHTML/onChange</code> output.</p>
<ul>
  <li>Edit content on the left</li>
  <li>See raw HTML render on the right</li>
  <li>Use Ctrl+S to test save callback</li>
</ul>`);

    return (
        <div
            style={{
                minHeight: '100vh',
                background: darkMode ? '#0f172a' : '#f8fafc',
                color: darkMode ? '#e2e8f0' : '#0f172a',
                fontFamily: 'system-ui, -apple-system, sans-serif',
                padding: '4rem 1.25rem 1.25rem',
            }}
        >
            <div style={{ maxWidth: '1400px', margin: '0 auto' }}>
                <div
                    style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        gap: '1rem',
                        marginBottom: '1rem',
                        flexWrap: 'wrap',
                    }}
                >
                    <div>
                        <h1 style={{ margin: 0, fontSize: '1.5rem' }}>Preview Page (Direct HTML)</h1>
                        <p
                            style={{
                                margin: '0.35rem 0 0',
                                fontSize: '0.875rem',
                                color: darkMode ? '#94a3b8' : '#64748b',
                            }}
                        >
                            Editor output is rendered directly with <code>dangerouslySetInnerHTML</code>.
                        </p>
                    </div>

                    <div style={{ display: 'flex', gap: '0.5rem' }}>
                        <button
                            onClick={() => {
                                const latestHtml = editorRef.current?.getHTML();
                                if (latestHtml) {
                                    setContent(latestHtml);
                                }
                            }}
                            style={{
                                padding: '0.5rem 0.875rem',
                                borderRadius: '0.375rem',
                                border: `1px solid ${darkMode ? '#334155' : '#cbd5e1'}`,
                                background: darkMode ? '#1e293b' : '#ffffff',
                                color: darkMode ? '#e2e8f0' : '#0f172a',
                                cursor: 'pointer',
                            }}
                        >
                            Refresh From Ref
                        </button>
                        <button
                            onClick={() => setDarkMode((prev) => !prev)}
                            style={{
                                padding: '0.5rem 0.875rem',
                                borderRadius: '0.375rem',
                                border: `1px solid ${darkMode ? '#475569' : '#cbd5e1'}`,
                                background: darkMode ? '#334155' : '#ffffff',
                                color: darkMode ? '#e2e8f0' : '#0f172a',
                                cursor: 'pointer',
                            }}
                        >
                            {darkMode ? 'Light' : 'Dark'}
                        </button>
                    </div>
                </div>

                <div
                    style={{
                        display: 'grid',
                        gap: '1rem',
                        gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
                    }}
                >
                    <section
                        style={{
                            background: darkMode ? '#1e293b' : '#ffffff',
                            border: `1px solid ${darkMode ? '#334155' : '#e2e8f0'}`,
                            borderRadius: '0.5rem',
                            overflow: 'hidden',
                        }}
                    >
                        <div
                            style={{
                                padding: '0.75rem 1rem',
                                borderBottom: `1px solid ${darkMode ? '#334155' : '#e2e8f0'}`,
                                background: darkMode ? '#0f172a' : '#f8fafc',
                                fontWeight: 600,
                                fontSize: '0.875rem',
                            }}
                        >
                            Editor
                        </div>
                        <AuthorlyEditor
                            ref={editorRef}
                            initialContent={content}
                            onChange={setContent}
                            onSave={(html) => {
                                setContent(html);
                                console.log('Saved HTML:', html);
                            }}
                            darkMode={darkMode}
                            placeholder="Type here to see direct HTML preview..."
                            style={{ minHeight: '560px', padding: '1.25rem' }}
                        />
                    </section>

                    <section
                        style={{
                            background: darkMode ? '#1e293b' : '#ffffff',
                            border: `1px solid ${darkMode ? '#334155' : '#e2e8f0'}`,
                            borderRadius: '0.5rem',
                            overflow: 'hidden',
                            display: 'flex',
                            flexDirection: 'column',
                        }}
                    >
                        <div
                            style={{
                                padding: '0.75rem 1rem',
                                borderBottom: `1px solid ${darkMode ? '#334155' : '#e2e8f0'}`,
                                background: darkMode ? '#0f172a' : '#f8fafc',
                                fontWeight: 600,
                                fontSize: '0.875rem',
                            }}
                        >
                            HTML Preview (Direct Render)
                        </div>
                        <div style={{ padding: '1.25rem', overflow: 'auto', minHeight: '560px' }}>
                            <div className={`cbr-content${darkMode ? ' cbr-dark' : ''}`} dangerouslySetInnerHTML={{ __html: content }} />
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default PreviewPage;